### ISSUE TITLE
[feature request] show how many time the event occurred in the selected month

### ISSUE THREAD

**Issue by ghost** [BrunoBernardino/loggit-web#3]
Hi,

I just signed up and so far it looks very promising but for it to be perfect for my use case, I'd like to propose one feature.
![default](https://github.com/BrunoBernardino/loggit-web/assets/126724080/a34719f1-90d5-4d4b-adaa-87e6e37fe001)

Instead of just saying 4x / year, I'd like It to say 4x / year, 4x / the_selected month. So in this case it would read 4x/year, 4x/October 2023. So this way I can set and track my goals on a monthly basis if that makes sense.

Thank you for the app,
Remi

**Comment by BrunoBernardino** [comment]
Hi Rémi, thank you so much for this great idea! Would it be enough if I implemented the current month frequency on hover and on the clicked pop-up?

If not, I might do that and add a setting to change the default frequency that shows up there (with the other on hover).

**Comment by ghost** [comment]
@BrunoBernardino Yes absolutely. It would just be great to be provided with this information. I can understand why 4x/year, 4x/month might clutter the default view a bit too much. 

Edit: actually in my case, adding a setting to change the default frequency that shows up there would be even better because I don't really care about the yearly frequency.

**Comment by BrunoBernardino** [comment]
@rburettt the 4x/year will change as the frequency increases, and if you're consistently logging that event roughly 4x / month, it'll eventually show that. In any case, I added a new setting which you should see now (force a refresh to clear cache), which you can toggle to see those current month stats instead (so it'll show 4x, and eventually 2x / week or whatever frequency it ends up being). On hover you'll see the other stats, and you'll see both on the popover.

I hope that helps!

**Comment by ghost** [comment]
@BrunoBernardino Excellent, the new setting "Change displayed top event frequency" was exactly what I needed. I'm going to wait until my trial ends and will be happy to support you by buying the hosted version. Great work!
