### ISSUE TITLE
Docker Image Hosting / Docker Registry

### ISSUE THREAD

**Issue by jp1337** [BrunoBernardino/loggit-web#4]
Hello!
Thanks a lot for the development of this great project. I would like to install the software in my HomeLab under Kubernetes. Unfortunately I have not found where the Docker image is hosted. Is there a Docker registry that hosts the image?
For example, you could have a package pushed to the GitHub Docker Registry with every release. The Dockerfile already exists. The only thing missing is the automatic build and push of the image.

**Comment by BrunoBernardino** [comment]
Hi @jpylypiw Thanks for the kind words! I don't use it like that (I use it with `docker compose`, with a specialized `docker-compose.yml` tailored to my server's needs), so I'm not interested in maintaining such image, but you're welcome to build and push it (and/or make a PR for it to be done automatically)!

I hope that makes sense!
