### ISSUE TITLE
can't sign up user local instance

### ISSUE THREAD

**Issue by lgwapnitsky** [BrunoBernardino/loggit-web#7]
Whenever I try to sign up a user on a local instance, I'm receiving "invalid email/password". Is there a setting that is disallowing this?

**Comment by BrunoBernardino** [comment]
@lgwapnitsky is there an error you're seeing in the logs? Have you set `IS_UNSAFE_SELF_HOSTED="true"`  in your `.env` file?

**Comment by lgwapnitsky** [comment]
.env file

```
PORT=8000
BASE_URL="http://0.0.0.0:8000"

POSTGRESQL_HOST="localhost"
POSTGRESQL_USER="loggit"
POSTGRESQL_PASSWORD="PASSWORD"
POSTGRESQL_DBNAME="loggit"
POSTGRESQL_PORT=5432
POSTGRESQL_CAFILE=""

BREVO_API_KEY="fake"

STRIPE_API_KEY="fake"

# Uncomment this variable to log verification codes instead of emailing them, and create "lifetime" accounts on signup instead of trials
IS_UNSAFE_SELF_HOSTED="true" # any non-empty value will be considered true

```

![Screenshot from 2024-02-14 10-02-06](https://github.com/BrunoBernardino/loggit-web/assets/647444/252721b3-5381-43bd-94ad-9c11c00706b7)

As for logs, I do not see any log files.

**Comment by BrunoBernardino** [comment]
Are you running via `make start` or Docker? There should be direct output in `make start`, and for docker, it depends on how you're running it, but `docker-compose logs -f` should show something if you're using `docker-compose up -d`.

In the browser's console, do you have any information/error that could help understand what's happening if there are no errors in the server logs (for example, web crypto won't work without `https://` in Firefox)?

**Comment by lgwapnitsky** [comment]
Via make start. Very little output

**Comment by BrunoBernardino** [comment]
Ok, what about the browser? Can you inspect the console and the request for some more information? And in the database, is there any user entry?

**Comment by BrunoBernardino** [comment]
I'm closing this since there wasn't any new information in the last few months. Please let me know if you have any more new information.
